# ==============================================================================
# Configuration variables 
# ==============================================================================

# ------------------------------------------------------------------------------
# Configurable paths, mainly used with Grunt
# ------------------------------------------------------------------------------

# Grunt config and aliases
grunt: '.grunt'